version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/www
      - ./docker/php/ini/:/usr/local/etc/php/dev.conf.d/

  web:
    image: nginx
    ports:
      - "8080:80"

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3318:3306"

